language: go

go:
  - 1.8
  - 1.9
  - tip

services:
  - redis-server

before_install:

install:
  - go get github.com/garyburd/redigo/redis
  - go get github.com/northbright/ming800
  - go get github.com/northbright/redishelper
  - go get github.com/northbright/pathhelper
  - go get github.com/northbright/maphelper
  - go get github.com/shchnmz/ming
  - go get github.com/gin-gonic/gin

script:
  - go build
  - cd api && go build && cd ../
  - cd server && go build && cd ../
